[project]
name = "torch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "metriiics", email = "metriics@yandex.ru" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
torch = "torch:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
